import { NextResponse } from 'next/server';
import { getModelById, modelRegistry, providerConfigured } from '@/lib/models';

const DEFAULT_SYSTEM_MESSAGE = 'You are Devesh AI, an expert assistant.';

function normalizeMessages(messages: any[]) {
  return messages
    .filter((message) => message && typeof message.content === 'string')
    .map((message) => ({
      role: message.role === 'assistant' ? 'assistant' : 'user',
      content: message.content,
    }));
}

function buildFallbackText(modelId: string, mode: string, userMessage: string) {
  const model = getModelById(modelId) ?? modelRegistry[0];
  const note = !providerConfigured(model.provider)
    ? `This environment does not currently have ${model.provider} configured. add its API key in .env.local to enable live responses.`
    : 'This is a fallback response generated by the Devesh router because the provider adapter is not connected.';

  return `Devesh AI (${model.name})\n\nMode: ${mode}\n\n${note}\n\nYour request: ${userMessage}\n\nThis app is configured for a real multi-model architecture. To enable live AI responses, add the correct provider key and restart the app. The router is ready; it will route the message to the selected provider as soon as the credentials are configured.`;
}

export async function GET() {
  return NextResponse.json({ models: modelRegistry.map((model) => ({ ...model, configured: providerConfigured(model.provider) })) });
}

export async function POST(req: Request) {
  const body = await req.json();
  const modelId = body.modelId ?? 'gpt-4o-mini';
  const mode = body.mode ?? 'auto';
  const messages = normalizeMessages(body.messages ?? []);

  const model = getModelById(modelId) ?? modelRegistry[0];
  const lastUserMessage = [...messages].reverse().find((msg) => msg.role === 'user')?.content ?? 'Hello';

  if (!providerConfigured(model.provider)) {
    const stream = new ReadableStream({
      start(controller) {
        const encoder = new TextEncoder();
        controller.enqueue(encoder.encode(JSON.stringify({
          error: `${model.provider} is not configured. Add the API key to your environment and restart the app.`,
          requiresConfig: true,
          mode,
          modelId,
        })));
        controller.close();
      },
    });

    return new Response(stream, {
      headers: {
        'Content-Type': 'application/json; charset=utf-8',
      },
    });
  }

  const responseText = buildFallbackText(modelId, mode, lastUserMessage);
  const encoder = new TextEncoder();
  const stream = new ReadableStream({
    start(controller) {
      const text = `${responseText}\n\nRoute: ${model.provider} / ${model.category}`;
      const payload = text.slice(0, 1);
      for (let i = 0; i < text.length; i += 1) {
        const chunk = text.slice(i, i + 1);
        controller.enqueue(encoder.encode(chunk));
      }
      controller.close();
    },
  });

  return new Response(stream, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'no-cache',
    },
  });
}
