export const modelRegistry = [
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'OpenAI',
    category: 'General AI',
    description: 'Premium multimodal model for general chat and reasoning.',
    contextLength: '128k',
    supportsVision: true,
    supportsTools: true,
    supportsWebSearch: true,
    supportsImageGeneration: false,
    capabilities: ['chat', 'vision', 'tools'],
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'OpenAI',
    category: 'General AI',
    description: 'Fast, cost-efficient general AI assistant.',
    contextLength: '128k',
    supportsVision: true,
    supportsTools: true,
    supportsWebSearch: true,
    supportsImageGeneration: false,
    capabilities: ['chat', 'vision', 'tools'],
  },
  {
    id: 'o3-mini',
    name: 'o3 Mini',
    provider: 'OpenAI',
    category: 'Reasoning AI',
    description: 'Reasoning-first model optimized for analytical tasks.',
    contextLength: '200k',
    supportsVision: false,
    supportsTools: true,
    supportsWebSearch: true,
    supportsImageGeneration: false,
    capabilities: ['reasoning', 'math', 'coding'],
  },
  {
    id: 'claude-3-5-sonnet',
    name: 'Claude 3.5 Sonnet',
    provider: 'Anthropic',
    category: 'General AI',
    description: 'Strong writing, coding, and multimodal performance.',
    contextLength: '200k',
    supportsVision: true,
    supportsTools: true,
    supportsWebSearch: false,
    supportsImageGeneration: false,
    capabilities: ['writing', 'coding', 'vision'],
  },
  {
    id: 'claude-3-5-haiku',
    name: 'Claude 3.5 Haiku',
    provider: 'Anthropic',
    category: 'General AI',
    description: 'Fast and efficient for everyday tasks.',
    contextLength: '200k',
    supportsVision: true,
    supportsTools: true,
    supportsWebSearch: false,
    supportsImageGeneration: false,
    capabilities: ['fast', 'chat', 'vision'],
  },
  {
    id: 'gemini-1.5-pro',
    name: 'Gemini 1.5 Pro',
    provider: 'Google',
    category: 'General AI',
    description: 'Long-context multimodal model for content and coding.',
    contextLength: '1M',
    supportsVision: true,
    supportsTools: true,
    supportsWebSearch: true,
    supportsImageGeneration: false,
    capabilities: ['long-context', 'multimodal', 'research'],
  },
  {
    id: 'gemini-2.0-flash',
    name: 'Gemini 2.0 Flash',
    provider: 'Google',
    category: 'General AI',
    description: 'Fast general-purpose model for real-time tasks.',
    contextLength: '1M',
    supportsVision: true,
    supportsTools: true,
    supportsWebSearch: true,
    supportsImageGeneration: false,
    capabilities: ['fast', 'vision', 'chat'],
  },
  {
    id: 'grok-beta',
    name: 'Grok Beta',
    provider: 'xAI',
    category: 'General AI',
    description: 'Conversational model with real-time knowledge.',
    contextLength: '128k',
    supportsVision: false,
    supportsTools: true,
    supportsWebSearch: true,
    supportsImageGeneration: false,
    capabilities: ['chat', 'web'],
  },
  {
    id: 'grok-2',
    name: 'Grok 2',
    provider: 'xAI',
    category: 'Reasoning AI',
    description: 'Reasoning-focused model with strong analytical depth.',
    contextLength: '128k',
    supportsVision: false,
    supportsTools: true,
    supportsWebSearch: true,
    supportsImageGeneration: false,
    capabilities: ['reasoning', 'analysis'],
  },
  {
    id: 'llama-3.1-70b',
    name: 'Llama 3.1 70B',
    provider: 'Meta',
    category: 'Open/Alternative Models',
    description: 'Open-weight general model with broad compatibility.',
    contextLength: '128k',
    supportsVision: false,
    supportsTools: true,
    supportsWebSearch: false,
    supportsImageGeneration: false,
    capabilities: ['open-weight', 'chat'],
  },
  {
    id: 'llama-3.1-8b',
    name: 'Llama 3.1 8B',
    provider: 'Meta',
    category: 'Open/Alternative Models',
    description: 'Lightweight open model for lower-cost workloads.',
    contextLength: '128k',
    supportsVision: false,
    supportsTools: false,
    supportsWebSearch: false,
    supportsImageGeneration: false,
    capabilities: ['fast', 'open-weight'],
  },
  {
    id: 'deepseek-chat',
    name: 'DeepSeek Chat',
    provider: 'DeepSeek',
    category: 'Open/Alternative Models',
    description: 'Strong general AI with efficient response quality.',
    contextLength: '64k',
    supportsVision: false,
    supportsTools: true,
    supportsWebSearch: false,
    supportsImageGeneration: false,
    capabilities: ['chat', 'coding'],
  },
  {
    id: 'deepseek-reasoner',
    name: 'DeepSeek Reasoner',
    provider: 'DeepSeek',
    category: 'Reasoning AI',
    description: 'Advanced reasoning model for math and logic tasks.',
    contextLength: '64k',
    supportsVision: false,
    supportsTools: true,
    supportsWebSearch: false,
    supportsImageGeneration: false,
    capabilities: ['math', 'logic', 'reasoning'],
  },
  {
    id: 'qwen2.5-72b',
    name: 'Qwen 2.5 72B',
    provider: 'Qwen',
    category: 'Open/Alternative Models',
    description: 'Multilingual open-weight model for broad use cases.',
    contextLength: '128k',
    supportsVision: true,
    supportsTools: true,
    supportsWebSearch: false,
    supportsImageGeneration: false,
    capabilities: ['multilingual', 'chat'],
  },
  {
    id: 'qwen-coder',
    name: 'Qwen Coder',
    provider: 'Qwen',
    category: 'Coding AI',
    description: 'Open coding model for implementation-heavy tasks.',
    contextLength: '128k',
    supportsVision: false,
    supportsTools: true,
    supportsWebSearch: false,
    supportsImageGeneration: false,
    capabilities: ['coding', 'refactor', 'debugging'],
  },
  {
    id: 'mistral-large',
    name: 'Mistral Large',
    provider: 'Mistral',
    category: 'Open/Alternative Models',
    description: 'High-performance starter model with enterprise utility.',
    contextLength: '128k',
    supportsVision: false,
    supportsTools: true,
    supportsWebSearch: false,
    supportsImageGeneration: false,
    capabilities: ['enterprise', 'chat'],
  },
  {
    id: 'mistral-small',
    name: 'Mistral Small',
    provider: 'Mistral',
    category: 'Open/Alternative Models',
    description: 'Compact model for rapid responses and low latency.',
    contextLength: '32k',
    supportsVision: false,
    supportsTools: false,
    supportsWebSearch: false,
    supportsImageGeneration: false,
    capabilities: ['fast', 'lightweight'],
  },
  {
    id: 'command-r-plus',
    name: 'Command R Plus',
    provider: 'Cohere',
    category: 'Open/Alternative Models',
    description: 'Retrieval-grounded model with strong enterprise workflows.',
    contextLength: '128k',
    supportsVision: false,
    supportsTools: true,
    supportsWebSearch: true,
    supportsImageGeneration: false,
    capabilities: ['retrieval', 'research'],
  },
  {
    id: 'command-r',
    name: 'Command R',
    provider: 'Cohere',
    category: 'Open/Alternative Models',
    description: 'Balanced enterprise assistant model.',
    contextLength: '128k',
    supportsVision: false,
    supportsTools: true,
    supportsWebSearch: true,
    supportsImageGeneration: false,
    capabilities: ['chat', 'retrieval'],
  },
  {
    id: 'perplexity-sonar',
    name: 'Perplexity Sonar',
    provider: 'Perplexity',
    category: 'Research/Search AI',
    description: 'Web-first research model with citation-centric answers.',
    contextLength: '128k',
    supportsVision: false,
    supportsTools: true,
    supportsWebSearch: true,
    supportsImageGeneration: false,
    capabilities: ['research', 'citations', 'web'],
  },
  {
    id: 'gemini-grounded',
    name: 'Gemini Grounded',
    provider: 'Google',
    category: 'Research/Search AI',
    description: 'Google grounded model for current event-aware responses.',
    contextLength: '1M',
    supportsVision: true,
    supportsTools: true,
    supportsWebSearch: true,
    supportsImageGeneration: false,
    capabilities: ['grounded', 'research', 'multimodal'],
  },
  {
    id: 'openai-web',
    name: 'OpenAI Web Model',
    provider: 'OpenAI',
    category: 'Research/Search AI',
    description: 'OpenAI web-capable model for search-backed responses.',
    contextLength: '128k',
    supportsVision: true,
    supportsTools: true,
    supportsWebSearch: true,
    supportsImageGeneration: false,
    capabilities: ['web', 'search', 'chat'],
  },
  {
    id: 'custom-openai-compatible',
    name: 'Custom OpenAI Compatible',
    provider: 'OpenAI-compatible',
    category: 'Open/Alternative Models',
    description: 'Use compatible local or hosted OpenAI API endpoints.',
    contextLength: '128k',
    supportsVision: true,
    supportsTools: true,
    supportsWebSearch: false,
    supportsImageGeneration: false,
    capabilities: ['custom-api', 'integration'],
  },
];

export const defaultModels = modelRegistry;

export function getModelById(id: string) {
  return modelRegistry.find((model) => model.id === id) ?? modelRegistry[0];
}

export function providerConfigured(provider: string) {
  const lower = provider.toLowerCase();
  if (lower.includes('openai')) {
    return Boolean(process.env.OPENAI_API_KEY);
  }
  if (lower.includes('anthropic')) {
    return Boolean(process.env.ANTHROPIC_API_KEY);
  }
  if (lower.includes('google')) {
    return Boolean(process.env.GOOGLE_API_KEY);
  }
  if (lower.includes('xai')) {
    return Boolean(process.env.XAI_API_KEY);
  }
  if (lower.includes('deepseek')) {
    return Boolean(process.env.DEEPSEEK_API_KEY);
  }
  if (lower.includes('qwen')) {
    return Boolean(process.env.QWEN_API_KEY);
  }
  if (lower.includes('mistral')) {
    return Boolean(process.env.MISTRAL_API_KEY);
  }
  if (lower.includes('perplexity')) {
    return Boolean(process.env.PERPLEXITY_API_KEY);
  }
  if (lower.includes('cohere')) {
    return Boolean(process.env.COHERE_API_KEY);
  }
  if (lower.includes('meta')) {
    return Boolean(process.env.LLAMA_API_KEY || process.env.OPENAI_API_KEY);
  }
  return Boolean(process.env.OPENAI_API_KEY);
}
